import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from fpdf import FPDF

# --- 1. PAGE CONFIGURATION (Must be first) ---
st.set_page_config(page_title="Faura ROI Calculator", layout="wide")

# --- CUSTOM CSS FOR DOWNLOAD BUTTON ---
st.markdown("""
<style>
    div[data-testid="stDownloadButton"] > button {
        background-color: #007bff; 
        color: white;              
        border: none;
        border-radius: 8px;
        height: auto;              
        min-height: 60px;          
        width: 100%;               
        white-space: normal;       
        padding: 10px;
        font-weight: bold;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        transition: all 0.3s ease;
    }
    div[data-testid="stDownloadButton"] > button:hover {
        background-color: #0056b3; 
        color: white;
        box-shadow: 0 6px 8px rgba(0,0,0,0.2);
        transform: translateY(-2px);
    }
</style>
""", unsafe_allow_html=True)

# --- 2. STANDARDIZED LOGIN BLOCK ---
def check_password():
    """Returns `True` if the user had the correct password."""
    if st.session_state.get("password_correct", False):
        return True

    st.title("🔒 Faura Risk Calculator")
    
    with st.form("login_form"):
        st.write("Please enter the access code to view the calculator.")
        password = st.text_input("Password", type="password")
        submitted = st.form_submit_button("Log In")
        
        if submitted:
            if password == "Faura2026":
                st.session_state["password_correct"] = True
                st.rerun()
            else:
                st.error("😕 Password incorrect")
    return False

if not check_password():
    st.stop()

# --- 3. PDF GENERATOR FUNCTION ---
def create_pdf_report(client_name, metrics, inputs):
    class PDF(FPDF):
        def header(self):
            self.set_font('Helvetica', 'B', 20)
            self.cell(0, 10, 'Faura', new_x="LMARGIN", new_y="NEXT", align='L')
            self.set_font('Helvetica', 'I', 10)
            self.cell(0, 10, 'Underwriting Profitability Assessment', new_x="LMARGIN", new_y="NEXT", align='L')
            self.line(10, 30, 200, 30)
            self.ln(10)

        def footer(self):
            self.set_y(-15)
            self.set_font('Helvetica', 'I', 8)
            self.cell(0, 10, f'Page {self.page_no()} - Generated by Faura Analytics', align='C')

    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- SECTION 1: PORTFOLIO SNAPSHOT ---
    pdf.set_font("Helvetica", 'B', 14)
    pdf.cell(0, 10, f"Report For: {client_name}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", 'B', 10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 8, "  1. Portfolio & Risk Inputs", 0, 1, 'L', fill=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", size=10)
    col_width = 45
    row_height = 8

    pdf.cell(col_width, row_height, f"Homes: {inputs['n_homes']}", border=1)
    pdf.cell(col_width, row_height, f"Avg Premium: ${inputs['avg_premium']:,.0f}", border=1)
    pdf.cell(col_width, row_height, f"Avg TIV: ${inputs['avg_tiv']:,.0f}", border=1)
    pdf.cell(col_width, row_height, f"Incident Prob: {inputs['incident_prob']*100:.1f}%", border=1, new_x="LMARGIN", new_y="NEXT")
    
    pdf.cell(col_width, row_height, f"Expense Ratio: {inputs['expense_ratio']*100:.1f}%", border=1)
    pdf.cell(col_width, row_height, f"MDR (Unmit): {inputs['mdr_unmitigated']*100:.0f}%", border=1)
    pdf.cell(col_width, row_height, f"MDR (Mitigated): {inputs['mdr_mitigated']*100:.0f}%", border=1)
    pdf.cell(col_width, row_height, f"Conversion: {inputs['conversion_rate']*100:.0f}%", border=1, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # --- SECTION 2: EXECUTIVE SUMMARY ---
    pdf.set_font("Helvetica", 'B', 10)
    pdf.cell(0, 8, "  2. Executive Summary", 0, 1, 'L', fill=True)
    pdf.ln(2)

    profit_delta = metrics['faura_profit'] - metrics['sq_profit']
    claims_saved = metrics['sq_losses'] - metrics['faura_losses']
    
    # Combined Ratio Logic
    pdf.set_font("Helvetica", size=12)
    pdf.cell(95, 10, "Combined Ratio Impact:", border=0)
    
    # Logic: Lower ratio is better
    cr_diff = metrics['sq_combined_ratio'] - metrics['faura_combined_ratio']
    # e.g. SQ=110%, Faura=90% -> diff = 20% point improvement
    
    pdf.set_font("Helvetica", 'B', 12)
    # If ratio improved (Faura < SQ), make it green
    if metrics['faura_combined_ratio'] < metrics['sq_combined_ratio']:
        pdf.set_text_color(0, 128, 0)
        arrow = "Improvement"
    else:
        pdf.set_text_color(200, 0, 0)
        arrow = "Worsened"
        
    pdf.cell(95, 10, f"{metrics['sq_combined_ratio']*100:.1f}% -> {metrics['faura_combined_ratio']*100:.1f}%", border=0, align='R', new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0) # Reset
    
    pdf.set_font("Helvetica", size=12)
    pdf.cell(95, 10, "Net Profit Increase (Delta):", border=0)
    pdf.set_font("Helvetica", 'B', 12)
    
    sign = ""
    if profit_delta > 0:
        pdf.set_text_color(0, 128, 0)
        sign = "+"
    elif profit_delta < 0:
        pdf.set_text_color(200, 0, 0)
    else:
        pdf.set_text_color(0, 0, 0)

    pdf.cell(95, 10, f"{sign}${profit_delta:,.0f}", border=0, align='R', new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)

    pdf.ln(5)

    # --- SECTION 3: FINANCIAL BREAKDOWN ---
    pdf.set_font("Helvetica", 'B', 10)
    pdf.cell(0, 8, "  3. Detailed Financial Breakdown", 0, 1, 'L', fill=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", 'B', 10)
    w_item = 80
    w_num = 35
    pdf.cell(w_item, 8, "Line Item", 1, 0, 'L')
    pdf.cell(w_num, 8, "Status Quo", 1, 0, 'R')
    pdf.cell(w_num, 8, "With Faura", 1, 0, 'R')
    pdf.cell(w_num, 8, "Diff", 1, 1, 'R')

    pdf.set_font("Helvetica", size=10)
    
    def add_row(label, sq_val, faura_val, is_total=False, inverse_color=False):
        if is_total:
            pdf.set_font("Helvetica", 'B', 10)
            pdf.set_fill_color(230, 230, 230)
        else:
            pdf.set_font("Helvetica", size=10)
            pdf.set_fill_color(255, 255, 255)
            
        diff = faura_val - sq_val
        pdf.cell(w_item, 8, label, 1, 0, 'L', fill=True)
        pdf.cell(w_num, 8, f"${sq_val:,.0f}", 1, 0, 'R', fill=True)
        pdf.cell(w_num, 8, f"${faura_val:,.0f}", 1, 0, 'R', fill=True)
        
        pdf.set_text_color(0, 0, 0)
        if diff > 0:
            if inverse_color: pdf.set_text_color(200, 0, 0)
            else:             pdf.set_text_color(0, 128, 0)
        elif diff < 0:
            if inverse_color: pdf.set_text_color(0, 128, 0)
            else:             pdf.set_text_color(200, 0, 0)
        
        pdf.cell(w_num, 8, f"${diff:,.0f}", 1, 1, 'R', fill=True)
        pdf.set_text_color(0, 0, 0)

    add_row("Gross Written Premium", metrics['total_premium'], metrics['total_premium'])
    add_row("(-) Underwriting Expenses", metrics['sq_expenses'], metrics['faura_expenses'], inverse_color=True)
    add_row("(-) Expected Incident Losses", metrics['sq_losses'], metrics['faura_losses'], inverse_color=True)
    add_row("(-) Faura Program Fees", 0, metrics['faura_program_cost'], inverse_color=True)
    add_row("(-) Incentives (Cards+Discounts)", 0, metrics['faura_incentives'], inverse_color=True)
    add_row("= NET UNDERWRITING PROFIT", metrics['sq_profit'], metrics['faura_profit'], is_total=True)

    pdf.ln(10)

    pdf.set_font("Helvetica", 'I', 8)
    pdf.multi_cell(0, 5, "Assessment Notes: This report is a generated scenario analysis based on the provided program inputs. "
                         "It projects potential financial outcomes if the defined conversion rates, mitigation effectiveness, "
                         "and cost structures are achieved. Actual results will vary based on realized program performance.")

    return bytes(pdf.output())

# --- 4. CALCULATOR INPUTS ---
st.title("🔥 Faura Underwriting Profit Calculator")

def currency_input(label, default_value, tooltip=None):
    user_input = st.sidebar.text_input(label, value=f"${default_value:,.0f}", help=tooltip)
    try:
        clean_val = float(user_input.replace('$', '').replace(',', '').strip())
    except ValueError:
        clean_val = default_value
        st.sidebar.error(f"Please enter a valid number for {label}")
    return clean_val

st.sidebar.header("1. Portfolio Inputs")
n_homes = st.sidebar.number_input("Number of Homes", value=100, step=1)
avg_premium = currency_input("Avg Premium per Home", 4200)
avg_tiv = currency_input("Avg TIV per Home", 1000000)

expense_ratio_input = st.sidebar.number_input("Expense Ratio (%)", value=15.0, step=0.1, format="%.2f")
expense_ratio = expense_ratio_input / 100

st.sidebar.markdown("---")
st.sidebar.header("2. Risk Inputs")
incident_prob_input = st.sidebar.number_input("Annual Incident Probability (%)", value=1.0, step=0.01, format="%.2f")
incident_prob = incident_prob_input / 100
mdr_unmitigated_input = st.sidebar.number_input("MDR (Unmitigated) %", value=80.0, step=0.1)
mdr_unmitigated = mdr_unmitigated_input / 100
mdr_mitigated_input = st.sidebar.number_input("MDR (Mitigated) %", value=30.0, step=0.1)
mdr_mitigated = mdr_mitigated_input / 100

st.sidebar.markdown("---")
st.sidebar.header("3. Faura Program Inputs")
faura_cost = currency_input("Faura Cost per Home", 30)
conversion_input = st.sidebar.number_input("Conversion Rate (%)", value=20.0, step=1.0)
conversion_rate = conversion_input / 100
gift_card = currency_input("Gift Card Incentive", 50)
premium_discount = currency_input("Premium Discount", 100)

def calculate_metrics():
    total_premium = n_homes * avg_premium
    total_uw_expense = total_premium * expense_ratio
    sq_losses = n_homes * avg_tiv * incident_prob * mdr_unmitigated
    sq_profit = total_premium - (total_uw_expense + sq_losses)
    
    # Combined Ratio (SQ) = (Losses + Expenses) / Premium
    sq_combined_ratio = (sq_losses + total_uw_expense) / total_premium if total_premium > 0 else 0

    n_converted = n_homes * conversion_rate
    n_unconverted = n_homes * (1 - conversion_rate)
    faura_loss_unconverted = n_unconverted * avg_tiv * incident_prob * mdr_unmitigated
    faura_loss_converted = n_converted * avg_tiv * incident_prob * mdr_mitigated
    faura_total_losses = faura_loss_unconverted + faura_loss_converted

    total_faura_fee = n_homes * faura_cost
    total_gift_cards = n_converted * gift_card
    total_discounts = n_converted * premium_discount
    
    faura_total_cost = total_uw_expense + faura_total_losses + total_faura_fee + total_gift_cards + total_discounts
    faura_profit = total_premium - faura_total_cost
    
    # Combined Ratio (Faura) = (Losses + All Expenses) / Premium
    # Note: Program Fees + Incentives are treated as Expenses here
    faura_all_expenses = total_uw_expense + total_faura_fee + total_gift_cards + total_discounts
    faura_combined_ratio = (faura_total_losses + faura_all_expenses) / total_premium if total_premium > 0 else 0

    return {
        "sq_profit": sq_profit,
        "sq_losses": sq_losses,
        "sq_expenses": total_uw_expense,
        "sq_combined_ratio": sq_combined_ratio,
        "faura_profit": faura_profit,
        "faura_losses": faura_total_losses,
        "faura_program_cost": total_faura_fee,
        "faura_incentives": total_gift_cards + total_discounts,
        "faura_expenses": total_uw_expense,
        "faura_combined_ratio": faura_combined_ratio,
        "total_premium": total_premium
    }

metrics = calculate_metrics()

# --- 5. DASHBOARD LAYOUT ---
col_header, col_btn = st.columns([3, 1], gap="small")

with col_header:
    st.markdown("### Status Quo vs. Active Mitigation")

with col_btn:
    report_inputs = {
        'n_homes': n_homes, 'avg_premium': avg_premium, 'avg_tiv': avg_tiv,
        'incident_prob': incident_prob, 'expense_ratio': expense_ratio,
        'mdr_unmitigated': mdr_unmitigated, 'mdr_mitigated': mdr_mitigated,
        'conversion_rate': conversion_rate
    }
    pdf_bytes = create_pdf_report(
        client_name="Portfolio Analysis",
        metrics=metrics,
        inputs=report_inputs
    )
    st.download_button("📥 Download\nDetailed Report", data=pdf_bytes, file_name="Faura_Underwriting_Report.pdf", mime="application/pdf", use_container_width=True)


c1, c2, c3, c4, c5 = st.columns(5)
with c1: st.metric("Status Quo Profit", f"${metrics['sq_profit']:,.0f}")

profit_diff = metrics['faura_profit'] - metrics['sq_profit']
with c2: st.metric("With Faura Profit", f"${metrics['faura_profit']:,.0f}", delta=f"${profit_diff:,.0f}")

claims_saved = metrics['sq_losses'] - metrics['faura_losses']
with c3: st.metric("🛡️ Claims Saved", f"${claims_saved:,.0f}", help="Gross reduction in expected losses.")

total_program_cost = metrics['faura_program_cost'] + metrics['faura_incentives']
with c4: st.metric("🧾 Total Program Cost", f"${total_program_cost:,.0f}", delta_color="inverse")

net_project_roi_dollars = claims_saved - total_program_cost
if total_program_cost > 0:
    if net_project_roi_dollars >= 0:
        multiplier = claims_saved / total_program_cost
        display_delta = f"{multiplier:.1f}x ROI Multiplier"
        delta_color = "normal"
    else:
        roi_pct = net_project_roi_dollars / total_program_cost
        display_delta = f"{roi_pct:.0%} Negative ROI"
        delta_color = "normal"
else:
    display_delta, delta_color = "N/A", "off"

with c5: st.metric("💰 Net Project ROI ($)", f"${net_project_roi_dollars:,.0f}", delta=display_delta, delta_color=delta_color)

st.markdown("---")

fig = go.Figure()
fig.add_trace(go.Bar(x=['Status Quo'], y=[metrics['sq_profit']], name='Status Quo', text=[f"${metrics['sq_profit']:,.0f}"], textposition='auto', marker_color='#EF553B'))
fig.add_trace(go.Bar(x=['With Faura'], y=[metrics['faura_profit']], name='With Faura', text=[f"${metrics['faura_profit']:,.0f}"], textposition='auto', marker_color='#4B604D'))
fig.update_layout(title="Net Underwriting Profit Comparison", height=500)
st.plotly_chart(fig, use_container_width=True)

st.subheader("Financial Breakdown")
table_data = {
    "Line Item": ["Gross Written Premium", "(-) Underwriting Expenses", "(-) Expected Incident Losses", "(-) Faura Program Fees", "(-) Incentives (Cards + Discounts)", "= NET PROFIT"],
    "Status Quo": [metrics['total_premium'], -metrics['sq_expenses'], -metrics['sq_losses'], 0, 0, metrics['sq_profit']],
    "With Faura": [metrics['total_premium'], -metrics['faura_expenses'], -metrics['faura_losses'], -metrics['faura_program_cost'], -metrics['faura_incentives'], metrics['faura_profit']]
}
df = pd.DataFrame(table_data)
def fmt(x): return f"${x:,.0f}"
df["Status Quo"], df["With Faura"] = df["Status Quo"].apply(fmt), df["With Faura"].apply(fmt)
def highlight_total(row): return ['font-weight: bold; background-color: #f0f2f6; color: black'] * len(row) if row.name == 5 else [''] * len(row)
st.table(df.style.apply(highlight_total, axis=1))

st.markdown("---")
with st.expander("ℹ️ Glossary & Formula Logic"):
    st.markdown("### 1. Variable Definitions\n* **MDR:** Mean Damage Ratio.\n* **TIV:** Total Insurable Value.")