import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from fpdf import FPDF

# --- 1. PAGE CONFIGURATION (Must be first) ---
st.set_page_config(page_title="Faura ROI Calculator", layout="wide")

# --- 2. STANDARDIZED LOGIN BLOCK ---
def check_password():
    """Returns `True` if the user had the correct password."""
    if st.session_state.get("password_correct", False):
        return True

    st.title("🔒 Faura Risk Calculator")
    
    with st.form("login_form"):
        st.write("Please enter the access code to view the calculator.")
        password = st.text_input("Password", type="password")
        submitted = st.form_submit_button("Log In")
        
        if submitted:
            if password == "Faura2026":
                st.session_state["password_correct"] = True
                st.rerun()
            else:
                st.error("😕 Password incorrect")
    return False

if not check_password():
    st.stop()

# --- 3. PDF GENERATOR FUNCTION ---
def create_pdf_report(client_name, metrics, inputs):
    """
    Generates a detailed PDF report including portfolio inputs and full P&L comparison.
    """
    class PDF(FPDF):
        def header(self):
            self.set_font('Helvetica', 'B', 20)
            self.cell(0, 10, 'Faura', new_x="LMARGIN", new_y="NEXT", align='L')
            self.set_font('Helvetica', 'I', 10)
            self.cell(0, 10, 'Underwriting Profitability Assessment', new_x="LMARGIN", new_y="NEXT", align='L')
            self.line(10, 30, 200, 30)
            self.ln(10)

        def footer(self):
            self.set_y(-15)
            self.set_font('Helvetica', 'I', 8)
            self.cell(0, 10, f'Page {self.page_no()} - Generated by Faura Analytics', align='C')

    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- SECTION 1: PORTFOLIO SNAPSHOT ---
    pdf.set_font("Helvetica", 'B', 14)
    pdf.cell(0, 10, f"Report For: {client_name}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", 'B', 10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 8, "  1. Portfolio & Risk Inputs", 0, 1, 'L', fill=True)
    pdf.ln(2)

    # Input Grid
    pdf.set_font("Helvetica", size=10)
    col_width = 45
    row_height = 8

    # Row 1
    pdf.cell(col_width, row_height, f"Homes: {inputs['n_homes']}", border=1)
    pdf.cell(col_width, row_height, f"Avg Premium: ${inputs['avg_premium']:,.0f}", border=1)
    pdf.cell(col_width, row_height, f"Avg TIV: ${inputs['avg_tiv']:,.0f}", border=1)
    pdf.cell(col_width, row_height, f"Incident Prob: {inputs['incident_prob']*100:.1f}%", border=1, new_x="LMARGIN", new_y="NEXT")
    
    # Row 2
    pdf.cell(col_width, row_height, f"Expense Ratio: {inputs['expense_ratio']*100:.1f}%", border=1)
    pdf.cell(col_width, row_height, f"MDR (Unmit): {inputs['mdr_unmitigated']*100:.0f}%", border=1)
    pdf.cell(col_width, row_height, f"MDR (Mitigated): {inputs['mdr_mitigated']*100:.0f}%", border=1)
    pdf.cell(col_width, row_height, f"Conversion: {inputs['conversion_rate']*100:.0f}%", border=1, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # --- SECTION 2: EXECUTIVE SUMMARY ---
    pdf.set_font("Helvetica", 'B', 10)
    pdf.cell(0, 8, "  2. Executive Summary", 0, 1, 'L', fill=True)
    pdf.ln(2)

    # Big "Value Created" Box
    profit_delta = metrics['faura_profit'] - metrics['sq_profit']
    claims_saved = metrics['sq_losses'] - metrics['faura_losses']
    
    pdf.set_font("Helvetica", size=12)
    pdf.cell(95, 10, "Net Profit Increase (Delta):", border=0)
    pdf.set_font("Helvetica", 'B', 12)
    pdf.set_text_color(0, 128, 0) # Green
    pdf.cell(95, 10, f"+${profit_delta:,.0f}", border=0, align='R', new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_text_color(0, 0, 0) # Reset color
    pdf.set_font("Helvetica", size=12)
    pdf.cell(95, 10, "Total Claims Avoided:", border=0)
    pdf.set_font("Helvetica", 'B', 12)
    pdf.cell(95, 10, f"${claims_saved:,.0f}", border=0, align='R', new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # --- SECTION 3: DETAILED FINANCIAL BREAKDOWN (The Table) ---
    pdf.set_font("Helvetica", 'B', 10)
    pdf.cell(0, 8, "  3. Detailed Financial Breakdown", 0, 1, 'L', fill=True)
    pdf.ln(2)

    # Table Header
    pdf.set_font("Helvetica", 'B', 10)
    w_item = 80
    w_num = 35
    pdf.cell(w_item, 8, "Line Item", 1, 0, 'L')
    pdf.cell(w_num, 8, "Status Quo", 1, 0, 'R')
    pdf.cell(w_num, 8, "With Faura", 1, 0, 'R')
    pdf.cell(w_num, 8, "Diff", 1, 1, 'R')

    # Rows
    pdf.set_font("Helvetica", size=10)
    
    def add_row(label, sq_val, faura_val, is_total=False):
        if is_total:
            pdf.set_font("Helvetica", 'B', 10)
            pdf.set_fill_color(230, 230, 230)
        else:
            pdf.set_font("Helvetica", size=10)
            pdf.set_fill_color(255, 255, 255)
            
        diff = faura_val - sq_val
        pdf.cell(w_item, 8, label, 1, 0, 'L', fill=True)
        pdf.cell(w_num, 8, f"${sq_val:,.0f}", 1, 0, 'R', fill=True)
        pdf.cell(w_num, 8, f"${faura_val:,.0f}", 1, 0, 'R', fill=True)
        
        # Color the difference
        if diff > 0 and is_total: pdf.set_text_color(0, 128, 0) # Green for profit gain
        elif diff < 0 and not is_total: pdf.set_text_color(200, 0, 0) # Red for higher costs
        
        pdf.cell(w_num, 8, f"${diff:,.0f}", 1, 1, 'R', fill=True)
        pdf.set_text_color(0, 0, 0) # Reset

    # 1. Premium
    add_row("Gross Written Premium", metrics['total_premium'], metrics['total_premium'])
    # 2. Expenses
    add_row("(-) Underwriting Expenses", metrics['sq_expenses'], metrics['faura_expenses'])
    # 3. Losses
    add_row("(-) Expected Incident Losses", metrics['sq_losses'], metrics['faura_losses'])
    # 4. Program Costs
    add_row("(-) Faura Program Fees", 0, metrics['faura_program_cost'])
    add_row("(-) Incentives (Cards+Discounts)", 0, metrics['faura_incentives'])
    # 5. NET PROFIT
    add_row("= NET UNDERWRITING PROFIT", metrics['sq_profit'], metrics['faura_profit'], is_total=True)

    pdf.ln(10)

    # --- SECTION 4: NOTES (REVISED) ---
    pdf.set_font("Helvetica", 'I', 8)
    # UPDATED DISCLAIMER TEXT PER REQUEST
    pdf.multi_cell(0, 5, "Assessment Notes: This report is a generated scenario analysis based on the provided program inputs. "
                         "It projects potential financial outcomes if the defined conversion rates, mitigation effectiveness, "
                         "and cost structures are achieved. Actual results will vary based on realized program performance.")

    return bytes(pdf.output())


# --- 4. CALCULATOR INPUTS & LOGIC ---

st.title("🔥 Faura Underwriting Profit Calculator")

def currency_input(label, default_value, tooltip=None):
    user_input = st.sidebar.text_input(label, value=f"${default_value:,.0f}", help=tooltip)
    try:
        clean_val = float(user_input.replace('$', '').replace(',', '').strip())
    except ValueError:
        clean_val = default_value
        st.sidebar.error(f"Please enter a valid number for {label}")
    return clean_val

# --- SIDEBAR INPUTS ---
st.sidebar.header("1. Portfolio Inputs")
n_homes = st.sidebar.number_input("Number of Homes", value=100, step=1)
avg_premium = currency_input("Avg Premium per Home", 10000)
avg_tiv = currency_input("Avg TIV per Home", 1000000)
expense_ratio_input = st.sidebar.number_input("Expense Ratio (%)", value=15.0, step=0.1, format="%.2f")
expense_ratio = expense_ratio_input / 100

st.sidebar.markdown("---")
st.sidebar.header("2. Risk Inputs")
incident_prob_input = st.sidebar.number_input("Annual Incident Probability (%)", value=1.0, step=0.01, format="%.2f")
incident_prob = incident_prob_input / 100
mdr_unmitigated_input = st.sidebar.number_input("MDR (Unmitigated) %", value=80.0, step=0.1)
mdr_unmitigated = mdr_unmitigated_input / 100
mdr_mitigated_input = st.sidebar.number_input("MDR (Mitigated) %", value=30.0, step=0.1)
mdr_mitigated = mdr_mitigated_input / 100

st.sidebar.markdown("---")
st.sidebar.header("3. Faura Program Inputs")
faura_cost = currency_input("Faura Cost per Home", 30)
conversion_input = st.sidebar.number_input("Conversion Rate (%)", value=20.0, step=1.0)
conversion_rate = conversion_input / 100
gift_card = currency_input("Gift Card Incentive", 50)
premium_discount = currency_input("Premium Discount", 100)

# --- CALCULATION LOGIC (MOVED UP) ---
# We calculate this BEFORE the layout so we can use the results in the Header Button
def calculate_metrics():
    total_premium = n_homes * avg_premium
    total_uw_expense = total_premium * expense_ratio
    sq_losses = n_homes * avg_tiv * incident_prob * mdr_unmitigated
    sq_profit = total_premium - (total_uw_expense + sq_losses)

    n_converted = n_homes * conversion_rate
    n_unconverted = n_homes * (1 - conversion_rate)
    faura_loss_unconverted = n_unconverted * avg_tiv * incident_prob * mdr_unmitigated
    faura_loss_converted = n_converted * avg_tiv * incident_prob * mdr_mitigated
    faura_total_losses = faura_loss_unconverted + faura_loss_converted

    total_faura_fee = n_homes * faura_cost
    total_gift_cards = n_converted * gift_card
    total_discounts = n_converted * premium_discount
    
    faura_total_cost = total_uw_expense + faura_total_losses + total_faura_fee + total_gift_cards + total_discounts
    faura_profit = total_premium - faura_total_cost

    return {
        "sq_profit": sq_profit,
        "sq_losses": sq_losses,
        "sq_expenses": total_uw_expense,
        "faura_profit": faura_profit,
        "faura_losses": faura_total_losses,
        "faura_program_cost": total_faura_fee,
        "faura_incentives": total_gift_cards + total_discounts,
        "faura_expenses": total_uw_expense,
        "total_premium": total_premium
    }

metrics = calculate_metrics()

# --- 5. DASHBOARD LAYOUT ---

# Top Header Area with Button on the Right
col_header, col_btn = st.columns([3, 1])

with col_header:
    st.markdown("### Status Quo vs. Active Mitigation")

with col_btn:
    # Gather inputs for report
    report_inputs = {
        'n_homes': n_homes, 'avg_premium': avg_premium, 'avg_tiv': avg_tiv,
        'incident_prob': incident_prob, 'expense_ratio': expense_ratio,
        'mdr_unmitigated': mdr_unmitigated, 'mdr_mitigated': mdr_mitigated,
        'conversion_rate': conversion_rate
    }
    # Generate PDF (Data is ready because we calculated it above)
    pdf_bytes = create_pdf_report(
        client_name="Portfolio Analysis",
        metrics=metrics,
        inputs=report_inputs
    )
    st.download_button("📥 Download Detailed Report", data=pdf_bytes, file_name="Faura_Underwriting_Report.pdf", mime="application/pdf", use_container_width=True)


# Metric Cards
c1, c2, c3, c4, c5 = st.columns(5)
with c1: st.metric("Status Quo Profit", f"${metrics['sq_profit']:,.0f}")

profit_diff = metrics['faura_profit'] - metrics['sq_profit']
with c2: st.metric("With Faura Profit", f"${metrics['faura_profit']:,.0f}", delta=f"${profit_diff:,.0f}")

claims_saved = metrics['sq_losses'] - metrics['faura_losses']
with c3: st.metric("🛡️ Claims Saved", f"${claims_saved:,.0f}", help="Gross reduction in expected losses.")

total_program_cost = metrics['faura_program_cost'] + metrics['faura_incentives']
with c4: st.metric("🧾 Total Program Cost", f"${total_program_cost:,.0f}", delta_color="inverse")

net_project_roi_dollars = claims_saved - total_program_cost
if total_program_cost > 0:
    if net_project_roi_dollars >= 0:
        multiplier = claims_saved / total_program_cost
        display_delta = f"{multiplier:.1f}x ROI Multiplier"
        delta_color = "normal"
    else:
        roi_pct = net_project_roi_dollars / total_program_cost
        display_delta = f"{roi_pct:.0%} Negative ROI"
        delta_color = "normal"
else:
    display_delta, delta_color = "N/A", "off"

with c5: st.metric("💰 Net Project ROI ($)", f"${net_project_roi_dollars:,.0f}", delta=display_delta, delta_color=delta_color)

st.markdown("---")

fig = go.Figure()
fig.add_trace(go.Bar(x=['Status Quo'], y=[metrics['sq_profit']], name='Status Quo', text=[f"${metrics['sq_profit']:,.0f}"], textposition='auto', marker_color='#EF553B'))
fig.add_trace(go.Bar(x=['With Faura'], y=[metrics['faura_profit']], name='With Faura', text=[f"${metrics['faura_profit']:,.0f}"], textposition='auto', marker_color='#4B604D'))
fig.update_layout(title="Net Underwriting Profit Comparison", height=500)
st.plotly_chart(fig, use_container_width=True)

st.subheader("Financial Breakdown")
table_data = {
    "Line Item": ["Gross Written Premium", "(-) Underwriting Expenses", "(-) Expected Incident Losses", "(-) Faura Program Fees", "(-) Incentives (Cards + Discounts)", "= NET PROFIT"],
    "Status Quo": [metrics['total_premium'], -metrics['sq_expenses'], -metrics['sq_losses'], 0, 0, metrics['sq_profit']],
    "With Faura": [metrics['total_premium'], -metrics['faura_expenses'], -metrics['faura_losses'], -metrics['faura_program_cost'], -metrics['faura_incentives'], metrics['faura_profit']]
}
df = pd.DataFrame(table_data)
def fmt(x): return f"${x:,.0f}"
df["Status Quo"], df["With Faura"] = df["Status Quo"].apply(fmt), df["With Faura"].apply(fmt)
def highlight_total(row): return ['font-weight: bold; background-color: #f0f2f6; color: black'] * len(row) if row.name == 5 else [''] * len(row)
st.table(df.style.apply(highlight_total, axis=1))

st.markdown("---")
with st.expander("ℹ️ Glossary & Formula Logic"):
    st.markdown("### 1. Variable Definitions\n* **MDR:** Mean Damage Ratio.\n* **TIV:** Total Insurable Value.")